[pytest]
pythonpath = .
addopts = -v --alluredir=reports/allure-results --browser-channel=chrome
testpaths =
    ui/tests
    api/tests
    tests
markers =
    smoke
    regression
    e2e
    negative: negative test scenarios
    api: api test
    contract