"""Converts TestScenario lists into pytest-compatible Python test files."""

from __future__ import annotations

import json
import re
import textwrap
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from web_discovery.scenario_generator.models import TestScenario

_IDENT_RE = re.compile(r"[^a-z0-9]+")


def _to_func_name(text: str) -> str:
    slug = _IDENT_RE.sub("_", text.lower()).strip("_")
    return f"test_{slug[:80]}"


def _step_to_code(step: dict, indent: str = "    ") -> str:
    stype = step.get("step_type", "")
    desc = step.get("description", "")
    sel = step.get("selector", "")
    url = step.get("url", "")
    value = step.get("value", "")
    assertion = step.get("assertion", "")

    lines: list[str] = [f"{indent}# {desc}" if desc else ""]

    if stype == "navigate":
        lines.append(f'{indent}page.goto({url!r}, wait_until="domcontentloaded")')
        lines.append(f'{indent}page.wait_for_load_state("networkidle", timeout=10000)')

    elif stype == "fill":
        lines.append(f"{indent}page.locator({sel!r}).fill({value!r})")

    elif stype == "click":
        lines.append(f"{indent}page.locator({sel!r}).click()")

    elif stype == "select":
        lines.append(f"{indent}page.locator({sel!r}).select_option({value!r})")

    elif stype == "check":
        lines.append(f"{indent}page.locator({sel!r}).check()")

    elif stype == "assert_visible":
        lines.append(f"{indent}expect(page.locator({sel!r})).to_be_visible()")

    elif stype == "assert_title":
        lines.append(f"{indent}expect(page).to_have_title(re.compile({re.escape(assertion)!r}))")

    elif stype == "assert_no_error":
        lines.append(
            f"{indent}assert page.locator({sel!r}).count() == 0, "
            '"Unexpected error message visible"'
        )

    elif stype == "assert_text":
        lines.append(f"{indent}expect(page.locator({sel!r})).to_contain_text({assertion!r})")

    return "\n".join(line for line in lines if line)


class ScriptGenerator:
    """Generates pytest files from TestScenario instances."""

    def __init__(self, output_dir: str | Path = "generated_tests") -> None:
        self._output_dir = Path(output_dir)

    def generate(self, scenarios: list[TestScenario], base_url: str = "") -> list[Path]:
        if not scenarios:
            return []
        self._output_dir.mkdir(parents=True, exist_ok=True)

        # Group by page URL
        groups: dict[str, list[TestScenario]] = {}
        for s in scenarios:
            groups.setdefault(s.page_url, []).append(s)

        written: list[Path] = []
        for url, group in groups.items():
            path = self._write_file(url, group, base_url)
            if path:
                written.append(path)

        # Write a conftest if not present
        conftest = self._output_dir / "conftest.py"
        if not conftest.exists():
            conftest.write_text(self._conftest_src(), encoding="utf-8")
            written.append(conftest)

        return written

    # ------------------------------------------------------------------

    def _write_file(
        self, page_url: str, scenarios: list[TestScenario], base_url: str
    ) -> Path | None:
        slug = _IDENT_RE.sub("_", page_url.replace(base_url, "").strip("/")).strip("_") or "root"
        slug = slug[:60]
        path = self._output_dir / f"test_wd_{slug}.py"

        src = self._file_src(page_url, scenarios)
        path.write_text(src, encoding="utf-8")
        return path

    def _file_src(self, page_url: str, scenarios: list[TestScenario]) -> str:
        header = textwrap.dedent(f"""\
            # AUTO-GENERATED by web_discovery — do not edit manually.
            # Source URL: {page_url}
            import re

            import pytest
            from playwright.sync_api import Page, expect


        """)

        body_parts: list[str] = []
        for s in scenarios:
            body_parts.append(self._scenario_src(s))

        return header + "\n\n".join(body_parts) + "\n"

    def _scenario_src(self, s: TestScenario) -> str:
        func = _to_func_name(s.name)
        marks = ""
        if s.tags:
            mark_list = ", ".join(f"pytest.mark.{t}" for t in s.tags)
            marks = f"@pytest.mark.parametrize('_', [pytest.param(None, marks=[{mark_list}])])\n"

        header = f"def {func}(page: Page) -> None:"
        docstring = f'    """{s.name}"""\n'

        step_lines: list[str] = []
        for step in s.steps:
            code = _step_to_code(step.to_dict() if hasattr(step, "to_dict") else step)
            if code.strip():
                step_lines.append(code)

        if not step_lines:
            step_lines = ["    pass"]

        body = "\n".join(step_lines)

        test_data_comment = ""
        if hasattr(s, "test_data") and s.test_data:
            td_json = json.dumps(s.test_data, indent=4)
            td_indented = textwrap.indent(td_json, "    # ")
            test_data_comment = f"    # Test data:\n{td_indented}\n"

        return f"{marks}{header}\n{docstring}{test_data_comment}{body}\n"

    @staticmethod
    def _conftest_src() -> str:
        return textwrap.dedent("""\
            # AUTO-GENERATED by web_discovery
            import pytest
            from playwright.sync_api import sync_playwright


            @pytest.fixture(scope="session")
            def browser_session():
                with sync_playwright() as pw:
                    browser = pw.chromium.launch(headless=True)
                    yield browser
                    browser.close()


            @pytest.fixture()
            def page(browser_session):
                ctx = browser_session.new_context()
                pg = ctx.new_page()
                yield pg
                ctx.close()
        """)
