"""Pytest plugin for web discovery — registers the engine when ENABLE_WEB_DISCOVERY=true."""

from __future__ import annotations

import logging
import os

logger = logging.getLogger(__name__)

_ENABLED = os.getenv("ENABLE_WEB_DISCOVERY", "false").lower() in ("1", "true", "yes")


def pytest_addoption(parser) -> None:
    group = parser.getgroup("web_discovery", "Autonomous Web Discovery")
    group.addoption(
        "--web-discovery",
        action="store_true",
        default=False,
        help="Run the web discovery engine before tests and collect generated tests.",
    )
    group.addoption(
        "--wd-target",
        default=os.getenv("WD_TARGET_URL", ""),
        help="Target URL for web discovery (overrides WD_TARGET_URL env var).",
    )
    group.addoption(
        "--wd-output",
        default=os.getenv("WD_OUTPUT_DIR", "generated_tests"),
        help="Output directory for generated tests.",
    )


def pytest_configure(config) -> None:
    config.addinivalue_line("markers", "generated: auto-generated by web_discovery")
    config.addinivalue_line("markers", "smoke: smoke test")
    config.addinivalue_line("markers", "happy_path: happy path scenario")
    config.addinivalue_line("markers", "negative: negative test scenario")
    config.addinivalue_line("markers", "edge_case: edge case scenario")
    config.addinivalue_line("markers", "navigation: navigation flow scenario")

    if not _ENABLED:
        return

    if not config.pluginmanager.hasplugin("web_discovery_plugin"):
        plugin = WebDiscoveryPlugin()
        config.pluginmanager.register(plugin, "web_discovery_plugin")


class WebDiscoveryPlugin:
    """Runs the discovery orchestrator before the test session starts."""

    def pytest_sessionstart(self, session) -> None:
        if not _ENABLED:
            return
        target = os.getenv("WD_TARGET_URL", "")
        if not target:
            logger.warning(
                "[web-discovery] ENABLE_WEB_DISCOVERY=true but WD_TARGET_URL is not set — skipping"
            )
            return

        try:
            from web_discovery.orchestrator import DiscoveryOrchestrator

            logger.info("[web-discovery] starting discovery run for %s", target)
            orchestrator = DiscoveryOrchestrator()
            result = orchestrator.run()
            logger.info("[web-discovery] %s", result.summary())

            # Make result available on the session for downstream fixtures
            session.wd_discovery_result = result
        except Exception as exc:  # noqa: BLE001
            logger.error(
                "[web-discovery] pipeline failed: %s — continuing without generated tests", exc
            )
            session.wd_discovery_result = None
