"""Generates flakiness reports in Markdown and JSON formats.

Markdown report is human-readable and suitable for Slack / PR comments.
JSON report is machine-readable for dashboards or trend analysis.
Both are written to reports/flakiness/ on each session end.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from autonomous_ui.flakiness.models import FlakinessProfile, FlakPattern, RemediationResult

# How many report pairs to keep on disk. See FlakinessReporter._prune.
_MAX_REPORT_PAIRS = 20

_SEVERITY_ICON = {"high": "CRITICAL", "medium": "WARNING", "low": "LOW"}
_PATTERN_LABEL = {
    FlakPattern.TIMING: "Timing / Wait",
    FlakPattern.ORDER_DEPENDENT: "Order-Dependent",
    FlakPattern.RESOURCE_CONTENTION: "Resource Contention",
    FlakPattern.DATA_POLLUTION: "Data Pollution",
    FlakPattern.ENVIRONMENT: "Environment",
    FlakPattern.UNKNOWN: "Unknown",
}


class FlakinessReporter:
    """Writes markdown and JSON flakiness reports to disk."""

    def generate_markdown(
        self,
        profiles: list[FlakinessProfile],
        analyses: dict[str, tuple[FlakPattern, RemediationResult]],
        run_ts: str | None = None,
    ) -> str:
        ts = run_ts or datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        flaky = [p for p in profiles if p.is_flaky]
        lines: list[str] = [
            f"# Flakiness Report — {ts}",
            "",
            "## Summary",
            "",
            f"- Tests tracked: {len(profiles)}",
            f"- Flaky tests detected: {len(flaky)}",
            f"- Stable tests: {len(profiles) - len(flaky)}",
        ]
        if flaky:
            worst = flaky[0]
            lines.append(f"- Highest flakiness: `{worst.test_id}` at {worst.flakiness_rate:.1%}")
        lines += ["", "---", "", "## Flaky Tests", ""]

        if not flaky:
            lines.append("No flaky tests detected in recorded history.")
        else:
            lines.append("| Test | Rate | Severity | Pattern | Runs | Max Consec. Failures |")
            lines.append("|---|---|---|---|---|---|")
            for p in flaky:
                pattern, _ = analyses.get(p.test_id, (FlakPattern.UNKNOWN, None))
                label = _PATTERN_LABEL.get(pattern, "Unknown")
                severity = _SEVERITY_ICON.get(p.severity, p.severity.upper())
                short_id = p.test_id.split("::")[-1]
                lines.append(
                    f"| `{short_id}` | {p.flakiness_rate:.1%} | {severity} "
                    f"| {label} | {p.total_runs} | {p.max_consecutive_failures} |"
                )

            lines += ["", "---", "", "## Recommendations", ""]
            for p in flaky:
                _, remediation = analyses.get(p.test_id, (None, None))
                if remediation:
                    lines += [
                        f"### `{p.test_id}`",
                        "",
                        f"**Strategy:** {remediation.strategy}",
                        "",
                        remediation.suggestion,
                        "",
                    ]

        lines += [
            "---",
            "",
            "*Generated by wiki_project autonomous flakiness intelligence.*",
        ]
        return "\n".join(lines)

    def generate_json(
        self,
        profiles: list[FlakinessProfile],
        analyses: dict[str, tuple[FlakPattern, RemediationResult]],
        run_ts: str | None = None,
    ) -> dict:
        ts = run_ts or datetime.now(tz=timezone.utc).isoformat()
        return {
            "generated_at": ts,
            "summary": {
                "total_tracked": len(profiles),
                "flaky_count": sum(1 for p in profiles if p.is_flaky),
                "stable_count": sum(1 for p in profiles if not p.is_flaky),
            },
            "flaky_tests": [
                {
                    "test_id": p.test_id,
                    "flakiness_rate": round(p.flakiness_rate, 4),
                    "severity": p.severity,
                    "total_runs": p.total_runs,
                    "failure_count": p.failure_count,
                    "confidence": round(p.confidence, 2),
                    "max_consecutive_failures": p.max_consecutive_failures,
                    "most_common_error": p.most_common_error[:300],
                    "pattern": analyses.get(p.test_id, (FlakPattern.UNKNOWN,))[0].value,
                    "strategy": (
                        analyses.get(p.test_id, (None, None))[1].strategy
                        if analyses.get(p.test_id, (None, None))[1]
                        else None
                    ),
                }
                for p in profiles
                if p.is_flaky
            ],
        }

    def write(
        self,
        profiles: list[FlakinessProfile],
        analyses: dict[str, tuple[FlakPattern, RemediationResult]],
        output_dir: Path = Path("reports/flakiness"),
        max_pairs: int = _MAX_REPORT_PAIRS,
    ) -> tuple[Path, Path]:
        """Write both reports to disk. Returns (markdown_path, json_path)."""
        output_dir.mkdir(parents=True, exist_ok=True)
        ts_str = datetime.now(tz=timezone.utc).strftime("%Y%m%dT%H%M%SZ")

        md_path = output_dir / f"report-{ts_str}.md"
        json_path = output_dir / f"report-{ts_str}.json"

        md_path.write_text(self.generate_markdown(profiles, analyses), encoding="utf-8")
        json_path.write_text(
            json.dumps(self.generate_json(profiles, analyses), indent=2), encoding="utf-8"
        )
        self._prune(output_dir, max_pairs)
        return md_path, json_path

    @staticmethod
    def _prune(output_dir: Path, max_pairs: int) -> None:
        """Keep only the newest ``max_pairs`` report pairs in *output_dir*.

        Nothing removed a report before this, and one pair is written per pytest
        invocation for as long as anything is flaky. In the source repo
        reports/flakiness/ held 664 files. They are also strictly superseded —
        each report is a full snapshot of the current history, so the newest one
        already says everything the older ones do.
        """
        if max_pairs < 1:
            return
        # Filenames are UTC timestamps in a sortable format, so lexical order is
        # chronological order.
        reports = (p for p in output_dir.glob("report-*") if p.suffix in (".md", ".json"))
        stems = sorted({p.stem for p in reports})
        for stem in stems[: max(0, len(stems) - max_pairs)]:
            for suffix in (".md", ".json"):
                try:
                    (output_dir / f"{stem}{suffix}").unlink(missing_ok=True)
                except OSError:
                    pass  # non-fatal — a stale report must not fail the run
