"""Wraps the graphifyy CLI to build and query knowledge graphs."""

import json
import os
import subprocess
from pathlib import Path


class GraphifyClient:
    """Drives the graphifyy CLI (pip install graphifyy) for knowledge graph operations."""

    def __init__(self, project_root: str | Path = "."):
        self.project_root = Path(project_root).resolve()
        self.graph_json = self.project_root / "graph.json"
        self.graph_html = self.project_root / "graph.html"
        self.cache_dir = self.project_root / "cache"

    # ------------------------------------------------------------------
    # Core operations
    # ------------------------------------------------------------------

    def build(self, mode: str = "standard") -> "BuildResult":
        """Run `graphify build` on the project root. Returns a BuildResult."""
        cmd = ["graphify", str(self.project_root)]
        if mode == "deep":
            cmd += ["--mode", "deep"]

        result = self._run(cmd)
        return BuildResult(
            success=result.returncode == 0,
            stdout=result.stdout,
            stderr=result.stderr,
            graph_json=self.graph_json if self.graph_json.exists() else None,
            graph_html=self.graph_html if self.graph_html.exists() else None,
        )

    def update(self) -> "BuildResult":
        """Incrementally update an existing graph (only re-processes changed files)."""
        cmd = ["graphify", str(self.project_root), "--update"]
        result = self._run(cmd)
        return BuildResult(
            success=result.returncode == 0,
            stdout=result.stdout,
            stderr=result.stderr,
            graph_json=self.graph_json if self.graph_json.exists() else None,
            graph_html=self.graph_html if self.graph_html.exists() else None,
        )

    def query(self, question: str) -> str:
        """Ask a natural-language question against the built graph."""
        cmd = ["graphify", "query", question, "--root", str(self.project_root)]
        result = self._run(cmd)
        if result.returncode != 0:
            return f"graphify query failed: {result.stderr}"
        return result.stdout.strip()

    def shortest_path(self, node_a: str, node_b: str) -> str:
        """Find the shortest path between two graph nodes."""
        cmd = ["graphify", "path", node_a, node_b, "--root", str(self.project_root)]
        result = self._run(cmd)
        if result.returncode != 0:
            return f"graphify path failed: {result.stderr}"
        return result.stdout.strip()

    # ------------------------------------------------------------------
    # Graph data access
    # ------------------------------------------------------------------

    def load_graph(self) -> dict:
        """Load the raw graph.json generated by the last build."""
        if not self.graph_json.exists():
            raise FileNotFoundError(
                f"graph.json not found at {self.graph_json}. Run build() first."
            )
        with self.graph_json.open() as f:
            return json.load(f)

    def is_built(self) -> bool:
        return self.graph_json.exists()

    def graph_stats(self) -> dict:
        """Return basic statistics about the current graph."""
        if not self.is_built():
            return {"built": False}
        g = self.load_graph()
        nodes = g.get("nodes", [])
        edges = g.get("edges", [])
        return {
            "built": True,
            "nodes": len(nodes),
            "edges": len(edges),
            "graph_json": str(self.graph_json),
            "graph_html": str(self.graph_html) if self.graph_html.exists() else None,
        }

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _run(self, cmd: list[str], timeout: int = 300) -> subprocess.CompletedProcess:
        env = {**os.environ}
        return subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            env=env,
            cwd=str(self.project_root),
        )


class BuildResult:
    def __init__(
        self,
        success: bool,
        stdout: str,
        stderr: str,
        graph_json: Path | None,
        graph_html: Path | None,
    ):
        self.success = success
        self.stdout = stdout
        self.stderr = stderr
        self.graph_json = graph_json
        self.graph_html = graph_html

    def __repr__(self) -> str:
        status = "OK" if self.success else "FAILED"
        return f"BuildResult({status}, nodes_json={self.graph_json})"
