"""GenerationAgent: generate pytest files from PostmanRequest objects."""

from __future__ import annotations

import ast
import logging
import re
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from api.agents.ingestion import PostmanRequest
    from api.engine.context_memory import ContextMemory
    from api.llm.base import BaseLLMClient

logger = logging.getLogger(__name__)

_SAFE_NAME = re.compile(r"[^a-zA-Z0-9_]")


def _slugify(text: str) -> str:
    return _SAFE_NAME.sub("_", text).lower().strip("_")


def _folder_key(req: PostmanRequest) -> str:
    return "_".join(req.folder_path) if req.folder_path else "default"


def _module_name_for_folder(folder_key: str) -> str:
    return f"test_{_slugify(folder_key)}.py"


def generated_module_name(req: PostmanRequest) -> str:
    """File name this request's test is written into, e.g. ``test_users.py``."""
    return _module_name_for_folder(_folder_key(req))


def generated_function_name(req: PostmanRequest) -> str:
    """Function name generated for this request, e.g. ``test_get_user_by_id``."""
    return f"test_{_slugify(req.name)}"


def generated_nodeid_suffix(req: PostmanRequest) -> str:
    """The ``file.py::function`` a pytest nodeid for this request will end with.

    This is the only reliable link between a Postman item and the test it turns
    into: the item name and the folder path are both slugified on the way in, so
    neither survives in a form a nodeid can be compared against. The full nodeid
    is out of reach here because the directory comes from ``output_dir``, which
    the caller chooses.

    Anything matching a nodeid to a request has to go through this, so the two
    cannot drift apart — the memory layer had its own idea of the naming and
    silently matched nothing for as long as it existed.
    """
    return f"{generated_module_name(req)}::{generated_function_name(req)}"


def _group_by_module(requests: list[PostmanRequest]) -> dict[str, list[PostmanRequest]]:
    """Group requests by the FILE they are written into, not by folder.

    The two are not the same thing: ``_module_name_for_folder`` slugifies and
    lower-cases, so the distinct Postman folders ``Users`` and ``users`` name one
    file. Grouping by folder meant the second group's ``write_text`` overwrote
    the first — its tests were gone, and ``generate()`` handed the same path back
    twice, so what survived was executed and healed twice over.
    """
    groups: dict[str, list[PostmanRequest]] = {}
    for req in requests:
        groups.setdefault(generated_module_name(req), []).append(req)
    return groups


def _indent(text: str, spaces: int = 4) -> str:
    """Indent every line of text by the given number of spaces."""
    prefix = " " * spaces
    return "\n".join(prefix + line if line.strip() else line for line in text.splitlines())


class GenerationAgent:
    """Generates pytest files from ingested PostmanRequest objects.

    Template-based generation works without an API key.
    LLM-enhanced generation produces richer assertions when a key is available.
    """

    def __init__(
        self,
        output_dir: str | Path = "generated_tests",
        llm: BaseLLMClient | None = None,
        memory: ContextMemory | None = None,
    ) -> None:
        self._output_dir = Path(output_dir)
        self._llm = llm
        self._memory = memory

    def generate(self, requests: list[PostmanRequest]) -> list[Path]:
        """Generate one pytest file per folder group.

        Returns list of generated file paths.
        """
        self._output_dir.mkdir(parents=True, exist_ok=True)
        groups = _group_by_module(requests)
        generated: list[Path] = []

        for module_name, module_requests in groups.items():
            file_path = self._output_dir / module_name
            content = self._render_module(module_requests)
            try:
                ast.parse(content)
            except SyntaxError as exc:
                # Writing this would hand the runner a file that cannot even be
                # collected, and healing would then be pointed at our own bug.
                raise ValueError(
                    f"Refusing to write {file_path}: generated source does not "
                    f"parse ({exc.msg} at line {exc.lineno})"
                ) from exc
            file_path.write_text(content, encoding="utf-8")
            logger.info("Generated: %s (%d tests)", file_path, len(module_requests))
            generated.append(file_path)

        return generated

    def _render_module(self, requests: list[PostmanRequest]) -> str:
        folders = sorted({_folder_key(req) for req in requests})
        lines: list[str] = [
            f'"""Auto-generated API tests for folder: {", ".join(folders)}.',
            "",
            "Generated by GenerationAgent. Do not edit by hand.",
            '"""',
            "import requests as http_requests",
            "",
            "from api.engine.validation import ValidationEngine, ValidationRules, measure_request",
            "",
            "",
        ]

        # Two items whose names slugify alike would produce two defs of one name,
        # and Python keeps the last — the same silent loss as an overwritten file,
        # one level down. It also makes generated_nodeid_suffix() ambiguous, so
        # nothing downstream could tell the two apart either. Say so instead.
        seen: dict[str, PostmanRequest] = {}
        test_blocks: list[str] = []
        for req in requests:
            fn_name = generated_function_name(req)
            clash = seen.get(fn_name)
            if clash is not None:
                raise ValueError(
                    f"Two requests generate the same test function {fn_name}(): "
                    f"{clash.folder_path}/{clash.name!r} and "
                    f"{req.folder_path}/{req.name!r}. Rename one in the collection."
                )
            seen[fn_name] = req
            test_blocks.append(self._render_test(req))

        return "\n".join(lines) + "\n\n".join(test_blocks) + "\n"

    def _render_test(self, req: PostmanRequest) -> str:
        fn_name = generated_function_name(req)
        method = req.method

        # Strip query string from URL if params will be passed separately,
        # to avoid duplicating query parameters.
        url = req.url.split("?")[0] if req.query_params and "?" in req.url else req.url

        # repr(), not json.dumps(): the output is Python source, and JSON's
        # true/false/null are bare names there. `body = {"active": true}` parses
        # — they are legal identifiers — and only dies with NameError once the
        # test runs, which analysis then filed under UNKNOWN forever.
        docstring = f"Test: {req.name} | {method} {req.url}"
        headers = req.headers or {}
        params = req.query_params or {}

        lines: list[str] = [
            f"def {fn_name}():",
            f"    {docstring!r}",
            "    engine = ValidationEngine()",
            f"    headers = {headers!r}",
            f"    params = {params!r}",
        ]

        call_kwargs: list[str] = []
        if req.body and req.body_mode == "raw_json":
            lines.append(f"    body = {req.body!r}")
            call_kwargs.append("json=body")
        elif req.body:
            # measure_request() takes a JSON body only, so a raw/urlencoded/
            # formdata body cannot be sent from here. Say it in the file rather
            # than issuing a request that quietly drops it.
            lines.append(
                f"    # body not sent: measure_request takes a JSON body only "
                f"(Postman mode: {req.body_mode})"
            )
        if req.query_params:
            call_kwargs.append("params=params")

        lines += [
            "    response, duration_ms = measure_request(",
            f"        {method!r},",
            f"        {url!r},",
            "        headers=headers,",
            *[f"        {kwarg}," for kwarg in call_kwargs],
            "        timeout=30,",
            "    )",
            "    rules = ValidationRules(",
            "        expected_status=200,",
            "        max_response_time_ms=5000,",
            "    )",
            "    result = engine.validate(response, rules, duration_ms=duration_ms)",
            '    assert result.passed, f"Validation failed: {result.failures}"',
        ]

        block = "\n".join(lines) + "\n"

        llm_extra = self._llm_assertions(req) if self._llm else ""
        if llm_extra:
            candidate = block + llm_extra + "\n"
            try:
                ast.parse(candidate)
            except SyntaxError as exc:
                # Model-written assertions are the one part of this file we did
                # not author. Drop them rather than lose the whole module.
                logger.warning(
                    "Discarding LLM assertions for %s: not valid Python (%s)", fn_name, exc.msg
                )
            else:
                block = candidate

        return block

    def _llm_assertions(self, req: PostmanRequest) -> str:
        if not self._llm:
            return ""
        prompt = (
            f"Generate 2-3 additional Python assert statements for this HTTP test:\n"
            f"Method: {req.method}\n"
            f"URL: {req.url}\n"
            f"Expected status: 200\n"
            f"Rules: check response time < 5s, response is valid JSON if Content-Type is JSON.\n"
            f"Return only the assert lines, no explanation, no imports."
        )
        # complete_result() names the failure instead of returning prose that a
        # prefix check has to sniff for; a sentinel string is indistinguishable
        # from a model answer that happens to start the same way.
        completion = self._llm.complete_result(prompt, max_tokens=256)
        if not completion.ok or not completion.text.strip():
            logger.debug("No LLM assertions for %s: %s", req.name, completion.failure)
            return ""
        # Indent each line as part of the function body
        indented = [f"    {line}" for line in completion.text.strip().splitlines() if line.strip()]
        return "\n".join(indented)
