"""TestGenerationAgent: generate pytest files from PostmanRequest objects."""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from api.agents.ingestion import PostmanRequest
    from api.engine.context_memory import ContextMemory
    from api.llm.base import BaseLLMClient

logger = logging.getLogger(__name__)

_SAFE_NAME = re.compile(r"[^a-zA-Z0-9_]")


def _slugify(text: str) -> str:
    return _SAFE_NAME.sub("_", text).lower().strip("_")


def _group_by_folder(requests: list[PostmanRequest]) -> dict[str, list[PostmanRequest]]:
    groups: dict[str, list[PostmanRequest]] = {}
    for req in requests:
        folder = "_".join(req.folder_path) if req.folder_path else "default"
        groups.setdefault(folder, []).append(req)
    return groups


def _indent(text: str, spaces: int = 4) -> str:
    """Indent every line of text by the given number of spaces."""
    prefix = " " * spaces
    return "\n".join(prefix + line if line.strip() else line for line in text.splitlines())


class TestGenerationAgent:
    """Generates pytest files from ingested PostmanRequest objects.

    Template-based generation works without an API key.
    LLM-enhanced generation produces richer assertions when a key is available.
    """

    def __init__(
        self,
        output_dir: str | Path = "generated_tests",
        llm: BaseLLMClient | None = None,
        memory: ContextMemory | None = None,
    ) -> None:
        self._output_dir = Path(output_dir)
        self._llm = llm
        self._memory = memory

    def generate(self, requests: list[PostmanRequest]) -> list[Path]:
        """Generate one pytest file per folder group.

        Returns list of generated file paths.
        """
        self._output_dir.mkdir(parents=True, exist_ok=True)
        groups = _group_by_folder(requests)
        generated: list[Path] = []

        for folder_name, folder_requests in groups.items():
            file_path = self._output_dir / f"test_{_slugify(folder_name)}.py"
            content = self._render_module(folder_name, folder_requests)
            file_path.write_text(content, encoding="utf-8")
            logger.info("Generated: %s (%d tests)", file_path, len(folder_requests))
            generated.append(file_path)

        return generated

    def _render_module(self, folder_name: str, requests: list[PostmanRequest]) -> str:
        lines: list[str] = [
            f'"""Auto-generated API tests for folder: {folder_name}.',
            "",
            "Generated by TestGenerationAgent. Do not edit by hand.",
            '"""',
            "import requests as http_requests",
            "",
            "from api.engine.validation import ValidationEngine, ValidationRules, measure_request",
            "",
            "",
        ]

        test_blocks: list[str] = []
        for req in requests:
            test_blocks.append(self._render_test(req))

        return "\n".join(lines) + "\n\n".join(test_blocks) + "\n"

    def _render_test(self, req: PostmanRequest) -> str:
        fn_name = f"test_{_slugify(req.name)}"
        method = req.method

        # Strip query string from URL if params will be passed separately,
        # to avoid duplicating query parameters.
        url = req.url.split("?")[0] if req.query_params and "?" in req.url else req.url

        headers_repr = json.dumps(req.headers) if req.headers else "{}"
        params_repr = json.dumps(req.query_params) if req.query_params else "{}"

        lines: list[str] = [
            f"def {fn_name}():",
            f'    """Test: {req.name} | {method} {req.url}"""',
            "    engine = ValidationEngine()",
            f"    headers = {headers_repr}",
            f"    params = {params_repr}",
        ]

        call_kwargs = ""
        if req.body and req.body_mode in ("raw_json", "raw"):
            try:
                body_str = json.dumps(req.body)
            except (TypeError, ValueError):
                body_str = repr(req.body)
            lines.append(f"    body = {body_str}")
            call_kwargs = ", json=body"

        if req.query_params:
            call_kwargs += ", params=params"

        lines += [
            "    response, duration_ms = measure_request(",
            f'        "{method}",',
            f'        "{url}",',
            "        headers=headers,",
            "        timeout=30,",
            "    )",
            "    rules = ValidationRules(",
            "        expected_status=200,",
            "        max_response_time_ms=5000,",
            "    )",
            "    result = engine.validate(response, rules, duration_ms=duration_ms)",
            '    assert result.passed, f"Validation failed: {result.failures}"',
        ]

        llm_extra = ""
        if self._llm:
            llm_extra = self._llm_assertions(req)
        if llm_extra:
            lines.append(llm_extra)

        return "\n".join(lines) + "\n"

    def _llm_assertions(self, req: PostmanRequest) -> str:
        if not self._llm:
            return ""
        prompt = (
            f"Generate 2-3 additional Python assert statements for this HTTP test:\n"
            f"Method: {req.method}\n"
            f"URL: {req.url}\n"
            f"Expected status: 200\n"
            f"Rules: check response time < 5s, response is valid JSON if Content-Type is JSON.\n"
            f"Return only the assert lines, no explanation, no imports."
        )
        result = self._llm.complete(prompt, max_tokens=256)
        if result and not result.startswith("Claude API error"):
            # Indent each line as part of the function body
            indented = [f"    {line}" for line in result.strip().splitlines() if line.strip()]
            return "\n".join(indented)
        return ""
