"""
State machine plugin — discovers transition methods and writes traversal stubs.

**It does not traverse anything, and it never did.** That is worth saying at the
top, because every part of the old version was arranged to look as though it
had.

A class qualified as a state machine by having an attribute named ``state``.
For such a class no transition method had been found, so the generator supplied
its own::

    transitions = sm.get("transitions", []) or ["init", "process", "complete", "error"]

Those four names came from nowhere — not from the class, not from the codebase.
They were then written into a generated test whose entire body was
``assert transition``, an assertion over a non-empty string constant that cannot
fail. The suite gained four green tests per class attesting to transitions that
do not exist. The same result then reported ``transition_counts`` of ``0`` for
that class, from the real (empty) list, so the plugin contradicted itself inside
one findings dict and still returned ``pass``.

What is honest here is narrow: a class with methods whose names contain
"transition" really does have those methods, and that is all this can establish
statically. So:

- no invented transitions, ever — a class with a ``state`` attribute and no
  transition methods is reported as a **candidate** and the run returns
  ``unknown``, because discovery was asked for and did not succeed;
- the generated test ``pytest.skip``s instead of asserting a tautology, so it
  cannot be counted as coverage of a machine nobody has driven;
- the file name carries the source path, because two ``Runner`` classes in two
  modules both wrote ``test_sm_runner.py`` and the second silently overwrote
  the first;
- and the run itself returns ``skip``, not ``pass``. Generating a stub is not a
  verdict about the health of anything. See the module note in the report: this
  plugin can no longer reach ``pass``, and that is the accurate description of
  what it does rather than a defect in the reporting.
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

from plugins._base_plugin import BasePlugin, PluginPriority, PluginResult, PluginStatus
from plugins.tier4._source_scan import relative_key, scan_source_files

_OUT_DIR = Path("ai_generated_tests/state_machine")

_MAX_MACHINES = 10

_SM_TEMPLATE = '''"""Traversal stub for {class_name}, generated from {source}.

Generated by static discovery alone: the methods below were found on the class,
nothing was instantiated and no transition was driven. The body skips rather
than asserts, so a machine nobody has driven cannot be counted as covered.
"""
from __future__ import annotations

import pytest

_TRANSITIONS = {transitions_list}


@pytest.mark.parametrize("transition", _TRANSITIONS)
def test_{slug}_transition(transition: str) -> None:
    """Drive {class_name}.<transition> — not implemented."""
    pytest.skip(f"TODO: instantiate {class_name} from {source} and drive {{transition}}")
'''


class _StateMachineVisitor(ast.NodeVisitor):
    """Classes carrying transition methods, and classes that merely look the part."""

    def __init__(self) -> None:
        self.machines: list[dict] = []
        self.candidates: list[dict] = []

    def visit_ClassDef(self, node: ast.ClassDef) -> None:  # noqa: N802
        has_state = False
        transitions: list[str] = []

        for item in node.body:
            if isinstance(item, ast.FunctionDef | ast.AsyncFunctionDef):
                if "transition" in item.name.lower():
                    transitions.append(item.name)
            if isinstance(item, ast.Assign | ast.AnnAssign):
                targets = item.targets if isinstance(item, ast.Assign) else [item.target]
                for target in targets:
                    if isinstance(target, ast.Name) and target.id in (
                        "state",
                        "_state",
                        "current_state",
                    ):
                        has_state = True

        entry = {
            "class_name": node.name,
            "has_state_attr": has_state,
            "transitions": sorted(transitions),
        }
        if transitions:
            self.machines.append(entry)
        elif has_state:
            # Looks like a state machine and yields no transitions. This is the
            # case the old code filled in with four names of its own.
            self.candidates.append(entry)
        self.generic_visit(node)


def _slug(source: str, class_name: str) -> str:
    """A file-name stem unique to (module, class).

    ``test_sm_{class}.py`` collided whenever two modules defined classes with
    the same lowercased name, and the loser was simply overwritten.
    """
    raw = f"{source}_{class_name}".lower()
    return re.sub(r"[^a-z0-9]+", "_", raw).strip("_")


class StateMachineExhaustivePlugin(BasePlugin):
    name = "state-machine-exhaustive"
    priority = PluginPriority.NORMAL
    trigger_conditions = ["source_change", "manual"]

    def run(self, context: dict) -> PluginResult:
        source_dir = Path(context.get("source_dir", "."))
        is_dry = context.get("dry_run", False)

        scan = scan_source_files(source_dir)
        machines: list[dict] = []
        candidates: list[dict] = []
        for py_file in scan.files:
            try:
                tree = ast.parse(py_file.read_text(encoding="utf-8"))
            except Exception:  # noqa: BLE001
                continue
            visitor = _StateMachineVisitor()
            visitor.visit(tree)
            source = relative_key(py_file, source_dir)
            for entry in visitor.machines:
                machines.append({**entry, "file": source})
            for entry in visitor.candidates:
                candidates.append({**entry, "file": source})

        if is_dry:
            return PluginResult(
                status=PluginStatus.SKIP.value,
                findings=[
                    {
                        "state_machines": machines,
                        "state_only_candidates": candidates,
                        "count": len(machines),
                    }
                ],
                dry_run=True,
            )

        if scan.truncated:
            return PluginResult(
                status=PluginStatus.UNKNOWN.value,
                findings=[
                    {
                        "reason": f"source scan stopped at {scan.count} files; the tree "
                        f"under {source_dir} was not read in full"
                    }
                ],
            )

        generated = self._generate(machines[:_MAX_MACHINES])

        findings = {
            "state_machines": machines,
            "state_only_candidates": candidates,
            "generated_files": generated,
            # Read off the same list the stubs were written from, so this can no
            # longer disagree with the transitions the run reported.
            "transition_counts": {
                f"{sm['file']}::{sm['class_name']}": len(sm["transitions"]) for sm in machines
            },
            "nothing_was_traversed": True,
        }

        if candidates:
            findings["reason"] = (
                f"{len(candidates)} class(es) carry a state attribute and no transition "
                "method could be derived; no transition list was invented for them"
            )
            return PluginResult(status=PluginStatus.UNKNOWN.value, findings=[findings])

        # Generating stubs is not a verdict about the product, so it is scored
        # neither way. The old code returned pass for exactly this.
        findings["reason"] = (
            f"generated {len(generated)} traversal stub(s); no state machine was driven, "
            "so this run carries no verdict"
        )
        return PluginResult(status=PluginStatus.SKIP.value, findings=[findings])

    def _generate(self, machines: list[dict]) -> list[str]:
        _OUT_DIR.mkdir(parents=True, exist_ok=True)
        generated: list[str] = []
        for sm in machines:
            slug = _slug(sm["file"], sm["class_name"])
            out_file = _OUT_DIR / f"test_sm_{slug}.py"
            out_file.write_text(
                _SM_TEMPLATE.format(
                    class_name=sm["class_name"],
                    source=sm["file"],
                    slug=slug,
                    transitions_list=repr(sm["transitions"]),
                ),
                encoding="utf-8",
            )
            generated.append(str(out_file))
        return generated


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    ctx: dict = {"source_dir": "."}
    plugin = StateMachineExhaustivePlugin()
    result = plugin.dry_run(ctx) if args.dry_run else plugin.execute(ctx)
    print(f"status={result.status} findings={result.findings}")
    sys.exit(0 if result.status in ("pass", "warn", "skip") else 1)
